# 1. Imports

In [1]:
import subprocess

# 2. Ejecución

In [2]:
subprocess.run(['python', '-m', 'scripts.process_dataset'], check=True)

Selecting stations based on processing config
Calculating sea level pressure
Renaming provinces with various names to single name
Saving Spain datasets
CLM dataset creation: reducing scope + adding sea level
CLM dataset creation: getting full ERA5 dataset
CLM dataset creation: matching units and vars
CLM dataset creation: filling missing values in existing registers
CLM dataset creation: filling missing registers with ERA5 data
CLM dataaset creation: saving

CompletedProcess(args=['python', '-m', 'scripts.process_dataset'], returncode=0)

# 3. Comprobación

## 3.1. AEMET

In [3]:
import pandas as pd

In [4]:
df = pd.read_parquet('datasets/parquet/CURATED_AEMET.parquet')
df.drop(columns=['presMax', 'presMin', 'presMedia', 'nombre', 'provincia'])

,fecha,indicativo,tmed,tmax,tmin,velmedia,racha,hrMedia,prec,anio,mes,dia,diaAnio,altitud,longitud,latitud,mslp_media,mslp_max,mslp_min
0,1990-01-01,0016A,9.000000,12.600000,5.400000,0.6,5.0,89.0,0.0,1990,1,1,1,71,1.163611,41.145000,1019.633545,1021.398560,1017.868469
1,1990-01-01,0076,9.200000,14.400000,4.000000,3.6,NaN,74.0,0.0,1990,1,1,1,4,2.070000,41.292778,1017.840637,1018.591003,1017.090332
2,1990-01-01,0200E,9.200000,12.000000,6.400000,5.6,8.9,62.0,0.0,1990,1,1,1,408,2.124167,41.418335,1017.702637,1018.595337,1016.809937
3,1990-01-01,0367,7.000000,15.000000,-1.000000,1.7,5.0,82.0,0.0,1990,1,1,1,143,2.763056,41.911388,1020.399963,1021.468384,1019.331543
4,1990-01-01,1014,11.200000,15.400000,7.000000,2.2,11.1,88.0,14.1,1990,1,1,1,4,-1.792222,43.356945,1018.136780,1021.088135,1015.185364
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799333,2024-12-31,C429I,17.500000,21.200001,13.800000,5.0,9.7,54.0,0.0,2024,12,31,366,64,-16.561111,28.046944,1023.279663,1024.740479,1021.818787
799334,2024-12-31,C447A,13.300000,15.900000,10.700000,3.9,10.3,84.0,0.0,2024,12,31,366,632,-16.329445,28.477501,1026.920410,1028.267090,1025.573853
799335,2024-12-31,C449C,18.799999,21.600000,15.900000,2.8,6.9,65.0,0.0,2024,12,31,366,36,-16.255278,28.463333,1024.982300,1026.388184,1023.576477
799336,2024-12-31,C649I,19.200001,22.000000,16.500000,3.1,7.8,64.0,0.0,2024,12,31,366,24,-15.395278,27.917778,1022.195496,1023.749878,1020.641174
799337,2024-12-31,C929I,20.000000,21.600000,18.299999,6.7,10.3,57.0,0.0,2024,12,31,366,32,-17.888889,27.818890,1024.190430,1025.595581,1022.785217

In [5]:
df.drop(columns=['presMax', 'presMin', 'presMedia', 'nombre', 'provincia']).info()

<class 'pandas.DataFrame'>
RangeIndex: 799338 entries, 0 to 799337
Data columns (total 19 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   fecha       799338 non-null  datetime64[ns]
 1   indicativo  799338 non-null  category
 2   tmed        797261 non-null  float32
 3   tmax        797485 non-null  float32
 4   tmin        797298 non-null  float32
 5   velmedia    792692 non-null  float32
 6   racha       787871 non-null  float32
 7   hrMedia     792983 non-null  float32
 8   prec        762512 non-null  float32
 9   anio        799338 non-null  int16
 10  mes         799338 non-null  int8
 11  dia         799338 non-null  int8
 12  diaAnio     799338 non-null  int16
 13  altitud     799338 non-null  int16
 14  longitud    799338 non-null  float32
 15  latitud     799338 non-null  float32
 16  mslp_media  792115 non-null  float32
 17  mslp_max    792164 non-null  float32
 18  mslp_min    792149 non-null  float32
dtypes: category(1), datetime64[ns](1), float32(12), int16(3), int8(2)
memory usage: 50.3 MB

In [6]:
s_df = pd.read_csv('datasets/csv/CURATED_AEMET_stations.csv')
s_df

,latitud,provincia,altitud,indicativo,nombre,indsinop,longitud,n_dias_reales,n_dias_teoricos,n_dias_perdidos,...,nan_latitud,tmed,tmax,tmin,velmedia,racha,hrMedia,prec,presMax,presMin
0,39.554167,BALEARES,3,B228,"PALMA, PUERTO",8301.0,2.625278,17167.0,17167.0,0.0,...,0.0,0.001017,0.000782,0.001017,0.006492,0.002190,0.003676,0.038094,0.023154,0.023154
1,39.560833,BALEARES,5,B278,"PALMA DE MALLORCA, AEROPUERTO",8306.0,2.736667,19146.0,19146.0,0.0,...,0.0,0.001408,0.001330,0.001330,0.010873,0.011733,0.004537,0.069540,0.000782,0.000782
2,39.854722,BALEARES,91,B893,"MENORCA, AEROPUERTO",8314.0,4.215556,20089.0,20089.0,0.0,...,0.0,0.001643,0.001486,0.001564,0.025031,0.028004,0.001956,0.091834,0.001877,0.001877
3,38.876389,ILLES BALEARS,6,B954,"IBIZA, AEROPUERTO",8373.0,1.384444,20089.0,20089.0,0.0,...,0.0,0.002972,0.002738,0.002894,0.006492,0.006805,0.004146,0.068680,0.006101,0.006101
4,28.951944,LAS PALMAS,14,C029O,LANZAROTE AEROPUERTO,60040.0,-13.600278,19054.0,19054.0,0.0,...,0.0,0.001956,0.001956,0.001956,0.002112,0.002738,0.001252,0.030663,0.000939,0.000939
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,42.452222,LA RIOJA,353,9170,"LOGROÑO, AEROPUERTO",8084.0,-2.331111,20088.0,20089.0,1.0,...,0.0,0.000469,0.000469,0.000469,0.003286,0.006884,0.001252,0.053274,0.001252,0.001252
62,42.776944,NAVARRA,459,9263D,"PAMPLONA, AEROPUERTO",8085.0,-1.650000,18263.0,18263.0,0.0,...,0.0,0.006727,0.006414,0.006414,0.005319,0.006414,0.005006,0.053426,0.002112,0.002190
63,41.660556,ZARAGOZA,249,9434,"ZARAGOZA, AEROPUERTO",8160.0,-1.004167,20089.0,20089.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.000626,0.005397,0.001017,0.067037,0.000626,0.000704
64,41.626111,LLEIDA,186,9771C,LLEIDA,8171.0,0.598056,15310.0,15310.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.001252,0.002268,0.000704,0.085810,0.000782,0.000860
65,40.820278,TARRAGONA,50,9981A,ESTACIÓN DE TORTOSA (ROQUETES),8238.0,0.493333,20089.0,20089.0,0.0,...,0.0,0.000000,0.000000,0.000000,0.001486,0.001408,0.000078,0.066411,0.001643,0.001643

In [7]:
s_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 62 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   latitud                   66 non-null     float64
 1   provincia                 66 non-null     str
 2   altitud                   66 non-null     int64
 3   indicativo                66 non-null     str
 4   nombre                    66 non-null     str
 5   indsinop                  65 non-null     float64
 6   longitud                  66 non-null     float64
 7   n_dias_reales             66 non-null     float64
 8   n_dias_teoricos           66 non-null     float64
 9   n_dias_perdidos           66 non-null     float64
 10  fecha_min                 66 non-null     str
 11  fecha_max                 66 non-null     str
 12  proporcion_dias_perdidos  66 non-null     float64
 13  nan_fecha                 66 non-null     float64
 14  nan_indicativo            66 non-null     float64
 15  nan_nombre                66 non-null     float64
 16  nan_provincia             66 non-null     float64
 17  nan_tmed                  66 non-null     float64
 18  nan_tmax                  66 non-null     float64
 19  nan_tmin                  66 non-null     float64
 20  nan_horatmax              66 non-null     float64
 21  nan_horatmin              66 non-null     float64
 22  nan_horatmaxVarias        66 non-null     float64
 23  nan_horatminVarias        66 non-null     float64
 24  nan_velmedia              66 non-null     float64
 25  nan_racha                 66 non-null     float64
 26  nan_horaracha             66 non-null     float64
 27  nan_dir                   66 non-null     float64
 28  nan_dirVarias             66 non-null     float64
 29  nan_hrMedia               66 non-null     float64
 30  nan_hrMax                 66 non-null     float64
 31  nan_hrMin                 66 non-null     float64
 32  nan_horaHrMax             66 non-null     float64
 33  nan_horaHrMin             66 non-null     float64
 34  nan_horaHrMaxVarias       66 non-null     float64
 35  nan_horaHrMinVarias       66 non-null     float64
 36  nan_prec                  66 non-null     float64
 37  nan_precIp                66 non-null     float64
 38  nan_precAcum              66 non-null     float64
 39  nan_sol                   66 non-null     float64
 40  nan_presMax               66 non-null     float64
 41  nan_presMin               66 non-null     float64
 42  nan_horaPresMax           66 non-null     float64
 43  nan_horaPresMin           66 non-null     float64
 44  nan_horaPresMaxVarias     66 non-null     float64
 45  nan_horaPresMinVarias     66 non-null     float64
 46  nan_anio                  66 non-null     float64
 47  nan_mes                   66 non-null     float64
 48  nan_dia                   66 non-null     float64
 49  nan_diaAnio               66 non-null     float64
 50  nan_altitud               66 non-null     float64
 51  nan_longitud              66 non-null     float64
 52  nan_latitud               66 non-null     float64
 53  tmed                      66 non-null     float64
 54  tmax                      66 non-null     float64
 55  tmin                      66 non-null     float64
 56  velmedia                  66 non-null     float64
 57  racha                     66 non-null     float64
 58  hrMedia                   66 non-null     float64
 59  prec                      66 non-null     float64
 60  presMax                   66 non-null     float64
 61  presMin                   66 non-null     float64
dtypes: float64(56), int64(1), str(5)
memory usage: 35.4 KB

## 3.2. CLM - Imputado

In [8]:
df = pd.read_parquet('datasets_clm/main/AEMET_ERA5_daily.parquet').sort_values(['fecha', 'nombre']).reset_index(drop=True)
df

,fecha,indicativo,nombre,provincia,tmed,tmax,tmin,velmedia,racha,hrMedia,...,mes,dia,diaAnio,altitud,longitud,latitud,mslp_media,mslp_max,mslp_min,source
0,2010-01-01,4210Y,ABENÓJAR,CIUDAD REAL,279.669220,281.691162,276.241455,5.827767,16.670288,84.306030,...,1,1,1,718,-4.291945,38.898056,101423.617188,101862.937500,101181.562500,ERA5
1,2010-01-01,4070Y,ABIA DE OBISPALIA,CUENCA,275.750000,277.649994,273.750000,4.700000,13.600000,95.000000,...,1,1,1,1020,-2.395278,40.018890,101165.835938,101705.187500,100810.750000,AEMET
2,2010-01-01,8178D,ALBACETE,ALBACETE,280.949982,284.750000,277.149994,6.400000,16.100000,71.000000,...,1,1,1,674,-1.862222,39.005554,101086.367188,101373.742188,100798.992188,AEMET
3,2010-01-01,8175,ALBACETE BASE AÉREA,ALBACETE,280.049988,282.949982,277.149994,10.800000,21.100000,65.000000,...,1,1,1,702,-1.856389,38.954166,101319.593750,101787.601562,100851.578125,AEMET
4,2010-01-01,4089A,ALBERCA DE ZANCARA,CUENCA,278.944855,280.415771,275.478271,7.023742,20.083675,78.802048,...,1,1,1,858,-2.495833,39.516945,101229.898438,101710.937500,100893.000000,ERA5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339693,2024-12-31,4091Y,VILLARROBLEDO,ALBACETE,277.549988,283.149994,272.049988,1.700000,5.800000,90.000000,...,12,31,366,718,-2.592500,39.261944,103080.484375,103219.937500,102914.062500,AEMET
339694,2024-12-31,4148,VISO DEL MARQUÉS,CIUDAD REAL,276.949982,283.449982,270.549988,1.100000,4.700000,77.000000,...,12,31,366,804,-3.566667,38.518055,103076.578125,103225.460938,102927.671875,AEMET
339695,2024-12-31,7072Y,YESTE,ALBACETE,277.049988,280.049988,274.049988,1.283702,8.176818,88.000000,...,12,31,366,960,-2.293889,38.294998,103073.296875,103163.187500,102901.812500,AEMET
339696,2024-12-31,7066Y,"YESTE, EMBALSE FUENSANTA",ALBACETE,278.049988,283.049988,273.049988,1.620077,8.255919,88.000000,...,12,31,366,680,-2.218889,38.393333,103066.890625,103161.437500,102897.812500,AEMET
339697,2024-12-31,3021Y,ZAOREJAS,GUADALAJARA,276.250000,282.949982,269.549988,0.800000,4.200000,73.000000,...,12,31,366,1250,-2.199722,40.758335,103056.109375,103149.687500,102883.562500,AEMET

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 339698 entries, 0 to 339697
Data columns (total 22 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   fecha       339698 non-null  datetime64[ns]
 1   indicativo  339698 non-null  str
 2   nombre      339698 non-null  str
 3   provincia   339698 non-null  str
 4   tmed        339698 non-null  float32
 5   tmax        339698 non-null  float32
 6   tmin        339698 non-null  float32
 7   velmedia    339698 non-null  float32
 8   racha       339698 non-null  float32
 9   hrMedia     339698 non-null  float32
 10  prec        339698 non-null  float32
 11  anio        339698 non-null  int32
 12  mes         339698 non-null  int32
 13  dia         339698 non-null  int32
 14  diaAnio     339698 non-null  int32
 15  altitud     339698 non-null  int32
 16  longitud    339698 non-null  float32
 17  latitud     339698 non-null  float32
 18  mslp_media  339698 non-null  float32
 19  mslp_max    339698 non-null  float32
 20  mslp_min    339698 non-null  float32
 21  source      339698 non-null  str
dtypes: datetime64[ns](1), float32(12), int32(5), str(4)
memory usage: 45.2 MB

In [10]:
s_df = pd.read_csv('datasets_clm/aux/AEMET_stations.csv')
s_df

,latitud,provincia,altitud,indicativo,nombre,indsinop,longitud,n_dias_reales,n_dias_teoricos,n_dias_perdidos,...,nan_horaPresMin,nan_horaPresMaxVarias,nan_horaPresMinVarias,nan_anio,nan_mes,nan_dia,nan_diaAnio,nan_altitud,nan_longitud,nan_latitud
0,40.841667,GUADALAJARA,1062,3013,MOLINA DE ARAGÓN,8232.0,-1.878889,20054.0,20089.0,35.0,...,1859.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,40.758333,GUADALAJARA,1250,3021Y,ZAOREJAS,NaN,-2.199722,4126.0,4527.0,401.0,...,4126.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,40.571667,CUENCA,1214,3040Y,BETETA,NaN,-2.076389,5156.0,5702.0,546.0,...,5156.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,40.530278,CUENCA,928,3044X,CAÑIZARES,8230.0,-2.150000,4825.0,5627.0,802.0,...,1090.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,40.407778,GUADALAJARA,920,3085Y,PASTRANA,NaN,-2.953056,4394.0,4633.0,239.0,...,4394.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,39.005556,ALBACETE,674,8178D,ALBACETE,8279.0,-1.862222,15337.0,15341.0,4.0,...,1543.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
61,38.850556,ALBACETE,710,8198Y,ALMANSA,NaN,-1.063056,5011.0,5308.0,297.0,...,5011.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
62,40.103056,CUENCA,1160,8210Y,SALVACAÑETE,NaN,-1.503611,4014.0,4628.0,614.0,...,4014.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63,39.714444,CUENCA,815,8245Y,MIRA,NaN,-1.442500,5645.0,5700.0,55.0,...,5645.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
64,40.778611,GUADALAJARA,1185,9377Y,EL PEDREGAL,NaN,-1.568333,4545.0,5558.0,1013.0,...,4545.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## 3.3. CLM - Todo proveniente de ERA5

In [11]:
df = pd.read_parquet('datasets_clm/main/ERA5_daily.parquet')
df

,indicativo,fecha,nombre,provincia,mslp_media,mslp_max,mslp_min,racha,tmed,tmax,tmin,prec,velmedia,hrMedia
0,3040Y,2010-01-01,BETETA,CUENCA,101093.117188,101672.6875,100656.7500,18.649223,273.617950,274.234131,269.931396,1.997471e-03,7.047187,92.347664
1,3040Y,2010-01-02,BETETA,CUENCA,102107.171875,102300.3125,101732.8125,9.469638,273.976807,274.886963,271.631104,2.622604e-05,2.263909,91.404758
2,3040Y,2010-01-03,BETETA,CUENCA,101896.835938,102128.8750,101650.8125,10.459117,275.436798,277.429688,272.134277,1.025677e-03,2.648411,85.699039
3,3040Y,2010-01-04,BETETA,CUENCA,100917.625000,101463.9375,100360.2500,10.834210,277.233093,278.287598,276.276367,4.936218e-03,2.394596,97.369742
4,3040Y,2010-01-05,BETETA,CUENCA,100192.726562,100420.9375,100035.4375,6.945802,276.850830,276.561279,274.823486,3.514767e-03,0.676060,94.829201
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
339693,4195E,2024-12-27,"ALCORNOQUERA, PARQUE NACIONAL CABAÑEROS",CIUDAD REAL,102857.757812,103096.6250,102673.8750,7.001990,278.741241,283.783936,274.901855,1.907349e-06,2.279331,84.112780
339694,4195E,2024-12-28,"ALCORNOQUERA, PARQUE NACIONAL CABAÑEROS",CIUDAD REAL,102998.187500,103228.8125,102784.6875,6.728862,278.057861,283.617188,274.943359,9.536743e-07,2.114268,81.058670
339695,4195E,2024-12-29,"ALCORNOQUERA, PARQUE NACIONAL CABAÑEROS",CIUDAD REAL,102867.835938,103008.6250,102691.1875,5.265178,276.934113,284.140625,272.495117,0.000000e+00,1.706835,80.475936
339696,4195E,2024-12-30,"ALCORNOQUERA, PARQUE NACIONAL CABAÑEROS",CIUDAD REAL,102957.210938,103097.0000,102807.6250,4.474727,276.196228,282.666016,272.336182,0.000000e+00,1.677345,86.051176
339697,4195E,2024-12-31,"ALCORNOQUERA, PARQUE NACIONAL CABAÑEROS",CIUDAD REAL,102984.734375,103098.9375,102812.5625,7.242248,276.339844,282.940674,271.391846,5.722046e-06,2.048529,83.103459